package-lock.json
package.json

@5.2.0 - html-snapshots ^1.6.0

---

package-lock.json
package.json

html-snapshots 1.9.0, close #45.

@5.3.2 - html-snapshots@1.9.0

---

package-lock.json
package.json

@5.7.0 - html-snapshots@1.16.1

---

package-lock.json
package.json

@6.5.2 - html-snapshots@2.7.2

---

package-lock.json
package.json

@6.6.0 - html-snapshots@2.8.0

---

package-lock.json
package.json

@6.8.1 - html-snapshots@2.10.1, devdep updates

---

package-lock.json
package.json

@6.9.1 - html-snapshots@2.11.1

---

package-lock.json
package.json

@6.10.0 - html-snapshots@2.12.2

---

package-lock.json
package.json

@6.11.1 - html-snapshots@2.13.1

---

Gruntfile.js
LICENSE.md
package-lock.json
package.json
tasks/html_snapshots.js

@6.11.3 - html-snapshots@2.13.3, copyright

---

package-lock.json
package.json

@6.12.0 - html-snapshots@2.14.0

---

package-lock.json
package.json

@6.14.0 - html-snapshots@2.16.0

---

package-lock.json
package.json

@7.4.1 - html-snapshots@3.4.1

---

package-lock.json
package.json

@7.6.0 - html-snapshots@3.6.0

---

package-lock.json
package.json

@7.6.3 - html-snapshots@3.6.3

---

package-lock.json
package.json

@7.7.1 - html-snapshots@3.7.1

---

package-lock.json
package.json

@7.8.0 - html-snapshots@3.8.0, devdeps

---

package-lock.json
package.json

@7.8.2 - html-snapshots@3.8.2

---

README.md
package-lock.json
package.json

@7.9.0 - html-snapshots@3.9.0, devdeps, readme

---

.github/workflows/verify.yml
package-lock.json
package.json

@7.10.0 - html-snapshots@3.10.0

---

package-lock.json
package.json

@7.10.2 - html-snapshots@3.10.2

---

package-lock.json
package.json

@7.11.0 - html-snapshots@3.11.0

---

package-lock.json
package.json

@7.11.2 - html-snapshots@3.11.2

---

package-lock.json
package.json

@7.13.0 - html-snapshots@3.13.0

---

.github/workflows/verify.yml
package-lock.json
package.json

@7.3.1 - html-snapshots@3.13.1

---

.github/workflows/verify.yml
package-lock.json
package.json

@7.14.0 - html-snapshots@3.14.0

---

package-lock.json
package.json

@7.15.0 - html-snapshots@3.15.0

---

package-lock.json
package.json

@8.0.2 - html-snapshots@4.0.2

---

package-lock.json
package.json

@8.1.1 - html-snapshots@4.1.1

---

package-lock.json
package.json

@8.2.1 - html-snapshots@4.2.1

---

.github/workflows/deploy.yml
.github/workflows/verify.yml
package-lock.json
package.json

@8.6.0 - html-snapshots@4.6.0, provenance
